# This is a sample configuration to run a Drupal-instance with Docker-Compose.
# For customization options see: https://docs.docker.com/compose/yml/

web:
  build: .
  #image: erasche/tripal:latest
  links:
    - db:postgres
  volumes:
    - /var/www/html/sites
    - /var/www/private
  environment:
    UPLOAD_LIMIT: 20M
    MEMORY_LIMIT: 128M
    BASE_URL: "http://localhost:3000"
    BASE_URL_PROTO: "http://"
  ports:
    - "3000:80"

db:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=password
  volumes:
    - /var/lib/postgresql/data
